# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: CmdLine@2
  inputs:
    script: 'C:\\SoftwareAG\\common\\AssetBuildEnvironment\\bin\\build.bat -Dbuild.output.dir=C:\\Users\\HariPrasad\\Box\\Learnings\\IS_Builds -Dbuild.source.project.dir=C:\\sers\\HariPrasad\\git\\webMethodsGIT\\assets\\IS\\packages -Denable.build.IS=true'
- task: BatchScript@1
  inputs:
    filename: 'C:/SoftwareAG/common/lib/ant/bin/ant.bat'
    arguments: '-f C:\Users\HariPrasad\workspace1015\cicdTest\deployer\updateAutomator.xml -Dbuild.output.dir=C:\Users\HariPrasad\Box\Learnings\IS_Builds'
- task: BatchScript@1
  inputs:
    filename: 'C:\SoftwareAG\IntegrationServer\instances\default\packages\WmDeployer\bin\projectautomator.bat'
    arguments: 'C:\Users\HariPrasad\workspace1015\cicdTest\deployer\Deployment_ProjectAutomator.xml'
- task: BatchScript@1
  inputs:
    filename: 'C:\SoftwareAG\IntegrationServer\instances\default\packages\WmDeployer\bin\Deployer.bat'
    arguments: '--deploy -dc Deployment_Candidate -project Deployment_Project -host localhost -port 5555 -user Administrator -pwd manage123'
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
