<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getInterfaceConfFilePath</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBudWxsOwp0cnkgewoJcGlwZWxpbmVDdXJzb3Ig
PSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKCVN0cmluZyBwYWNrYWdlTmFtZSA9IElEYXRhVXRpbC5n
ZXRTdHJpbmcgKHBpcGVsaW5lQ3Vyc29yLCAicGFja2FnZU5hbWUiKTsKCWlmIChwYWNrYWdlTmFt
ZSA9PSBudWxsKQoJCXRocm93IG5ldyBJbGxlZ2FsQXJndW1lbnRFeGNlcHRpb24oIkludGVyZmFj
ZSBwYWNrYWdlTmFtZSBpcyBudWxsIik7CgovLwlTdHJpbmcgY29uZmlnRmlsZVBhdGggPSBTeXN0
ZW0uZ2V0UHJvcGVydHkoQ09ORklHX0ZJTEVfUFJPUEVSVFlfTkFNRSk7Ci8vCWlmIChjb25maWdG
aWxlUGF0aCA9PSBudWxsKSB7CgkJRmlsZSBjb25maWdEaXIgPSBTZXJ2ZXJBUEkuZ2V0UGFja2Fn
ZUNvbmZpZ0RpcihwYWNrYWdlTmFtZSk7CgkJU3RyaW5nIGNvbmZpZ0RpclN0ciA9IGNvbmZpZ0Rp
ci5nZXRDYW5vbmljYWxQYXRoKCk7CgkJU3RyaW5nIGNvbmZpZ0ZpbGVQYXRoID0gY29uZmlnRGly
U3RyICsgIi8iICsgQ09ORklHX0ZJTEVfTkFNRTsKLy8JfQoKCUlEYXRhVXRpbC5wdXQocGlwZWxp
bmVDdXJzb3IsICJjb25maWdGaWxlUGF0aCIsIGNvbmZpZ0ZpbGVQYXRoKTsKfSBjYXRjaCAoRXhj
ZXB0aW9uIGV4KSB7Cgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihleCk7Cn0gZmluYWxseSB7
CglpZiAocGlwZWxpbmVDdXJzb3IgIT0gbnVsbCkKCQlwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7
Cn0=</value>
</Values>
